language: node_js
node_js:
  - "8"
before_script:
  - npm install -g firebase-tools
  - npm install -g next
script:
  - npm run test
  - npm run lint
after_script:
  - firebase deploy --token "$FIREBASE_TOKEN"
