language: node_js
node_js:
  - '8'

cache:
  directories:
    - 'node_modules'

install:
  - npm install

before_script:
  - npm run test
  - npm run lint

script:
  - npm run build:public && npm run build:funcs && npm run build:app && npm run deps:copy

deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy:all
  on:
    branch: master
