language: node_js
node_js:
  - '8'

cache:
  directories:
    - 'node_modules'
    - '$HOME/.sonar/cache'

install:
  - npm install

before_script:
  - npm run test:ci
  - npm run lint:ci
  - sonar-scanner

addons:
  sonarcloud:
    organization: "hmartinezdev-github" # the key of the org you chose at step #3
script:
  

script:
  - npm run server:copy && npm run build:public && npm run build:funcs && npm run build:app && npm run deps:copy

deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy:all
  on:
    branch: master
