language: node_js

node_js:
  - 8.16

cache:
  yarn: true
  directories:
    - node_modules
    - '$HOME/.sonar/cache'

install:
  - yarn install

before_script:
  - yarn run test:ci
  - yarn run lint:ci
  - sonar-scanner -X

script:
  - yarn run server:copy && yarn run build:public && yarn run build:funcs && yarn run
    build:app && yarn run deps:copy

deploy:
  skip_cleanup: true
  provider: script
  script: yarn run deploy:all
  on:
    branch: master

env:
  global:
    secure: WvsF+KH4CXO3azepUkhpeEcpLc4u8XYsiHt2FrfX3TC2QD30HhgsQL6k4mCiQsQbQWzZv3MR9o7mod+EXvKcdzj6OWgEZtMvQpbbgAJFcc7MTZx3746ikPeuwaND/2HxS/0+a50CkpSy8YwHU33McWQ2O3Tig9W4ZG5nbarf3IG5owQsxpYH8UYFT/8KBZLmnQSAs+iNIpE4qfvubeFAct/mT0MaoisImsNib+AbAa+vC93Pu69WdOfkc/Lgeezxnb4GgGGm+qjJDcBZYPDcoqNyUJT5uehHmyLGFz9IAk4myTvdOA2M3X68+KQMJfCs/+yDyRvlu/VB+tu9tGXETETAJlYQeJHjZkaOPYyZWcNLgI160NgPcy3i/5lDwR+bYu+4CN8BIJoub3NkhSDdbxYi9nF/DRJ8yuBUC1QpJXihDWLne7deieq53AmIU+B8gkV71WL7X2DzNEuVRHpkSDdmGrjMiUo+C+cNsXnVDekqzfscpFG3hZb/4iuFwgc3CDjib3FOQ8Dznr+5EFri6AEqnKTx92Cz6atBpLr559cjuIir+r/lU5bLZqRlBlhMTHG7DtFfeKFeUF94C4cyF6E59ygr8+uCN6qye4crHXtI/LyC0POffCGb1R8SlTT0CaoE3P355OWZTpYTjuRcEaR5v2kTyf6T5OJdo3hnPxY=
